name = "tecnova-api"
main = "src/index.ts"
compatibility_date = "2026-05-01"

[[d1_databases]]
binding = "DB"
database_name = "tecnova-db"
database_id = "4fddd4bd-5d1d-4f30-b2df-81fe75859e3a"
migrations_dir = "../../packages/db/drizzle"
